[project]
name = "langchain-rss"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "feedparser>=6.0.12",
    "lxml-html-clean>=0.4.3",
    "requests>=2.32.5",
    "sqlmodel>=0.0.27",
]
